# $Id$
#
# Makefile for the CDP module
# \author Dragos Vingarzan vingarzan -at- fokus dot fraunhofer dot de
#
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=isc.so

DEFS +=

LIBS= -L$(LOCALBASE)/lib 

DEFS += -I/usr/include/libxml2
LIBS += -lxml2

include ../../Makefile.modules
