# $Id$
#
# Makefile for the SIP2IMS module
# \author Dragos Vingarzan vingarzan -at- fokus dot fraunhofer dot de
#
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=sip2ims.so

include ../../Makefile.modules

