# Makefile v 1.0 2002/12/27
#
# Virtual Queue module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=vq.so
LIBS=

include ../../Makefile.modules
