# $Id$ Makefile  $Date$ $Author$ dvi
#
# example module makefile
#
#
# WARNING: do not run this directly, it should be run by the master Makefile



include ../../Makefile.defs
auto_gen=
NAME=scscf.so


DEFS += -I/usr/include/libxml2
LIBS += -lxml2

include ../../Makefile.modules



